from app.admin import routes_trainers  # noqa: F401
from app.admin import routes_registrations  # noqa: F401
from app.admin import routes_payments  # noqa: F401
from app.admin import routes_recaptcha  # noqa: F401
from app.admin import routes_analytics  # noqa: F401
from app.admin import routes_google_oauth  # noqa: F401
from app.admin import routes_apple_signin  # noqa: F401
from app.admin import routes_stubs  # noqa: F401
from app.admin import routes_uploads  # noqa: F401
from app.admin import routes_notifications  # noqa: F401
from app.admin import routes_notifications_recipients  # noqa: F401
from app.admin import routes_settings  # noqa: F401
from app.admin import routes_error_logs  # noqa: F401
from app.admin import routes_courses  # noqa: F401
from app.admin import routes_instances  # noqa: F401
from app.admin import routes_course_requests  # noqa: F401
from app.admin import routes_webhooks  # noqa: F401
from app.admin import routes_xlsx  # noqa: F401
from app.admin import routes_tools  # noqa: F401
