from app.admin import routes_trainers  # noqa: F401
from app.admin import routes_registrations  # noqa: F401
from app.admin import routes_payments  # noqa: F401
from app.admin import routes_stubs  # noqa: F401
from app.admin import routes_uploads  # noqa: F401
from app.admin import routes_notifications  # noqa: F401
from app.admin import routes_settings  # noqa: F401
from app.admin import routes_error_logs  # noqa: F401
from app.admin import routes_courses  # noqa: F401
from app.admin import routes_instances  # noqa: F401
from app.admin import routes_course_requests  # noqa: F401
from app.admin import routes_webhooks  # noqa: F401
