"""Add email_logs table

Revision ID: 28e0a72daba3
Revises: d9a4e6b83f21
Create Date: 2026-03-25 19:57:32.377370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e0a72daba3'
down_revision = 'd9a4e6b83f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.Column('registration_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_to_email'), ['to_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_trigger'), ['trigger'], unique=False)

    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_registrations_user_id_event_id_key'), type_='unique')
        batch_op.create_unique_constraint('uq_user_event_registration', ['user_id', 'event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_event_registration', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('event_registrations_user_id_event_id_key'), ['user_id', 'event_id'])

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_trigger'))
        batch_op.drop_index(batch_op.f('ix_email_logs_to_email'))
        batch_op.drop_index(batch_op.f('ix_email_logs_status'))
        batch_op.drop_index(batch_op.f('ix_email_logs_registration_id'))

    op.drop_table('email_logs')
    # ### end Alembic commands ###
