"""Add clinics table

Revision ID: 6481b908cc37
Revises: d841475f154a
Create Date: 2026-03-24 08:01:27.556716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6481b908cc37'
down_revision = 'd841475f154a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_is_active'))

    op.drop_table('clinics')
    # ### end Alembic commands ###
