"""Додати індекси created_at, composite status_trigger та таблицю payment_transactions

Revision ID: a20d49aa9261
Revises: c3d4e5f6a7b8
Create Date: 2026-03-26 20:30:59.259543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20d49aa9261'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('registration_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('liqpay_status', sa.String(length=50), nullable=True),
    sa.Column('mapped_status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mapped_status IN ('unpaid', 'pending', 'paid', 'refunded')", name='ck_payment_transactions_mapped_status'),
    sa.CheckConstraint("source IN ('callback', 'status_check', 'refund', 'manual')", name='ck_payment_transactions_source'),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_payment_transactions_reg_created', ['registration_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_registration_id'), ['registration_id'], unique=False)

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index('ix_email_logs_status_trigger', ['status', 'trigger'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_created_at')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_created_at')

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_email_logs_status_trigger')

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_registration_id'))
        batch_op.drop_index('ix_payment_transactions_reg_created')
        batch_op.drop_index(batch_op.f('ix_payment_transactions_order_id'))

    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
